language: python
distro: xenial

addons:
  apt:
    update: true
    packages:
      - cloc

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks ~/lua_install -r^ --$LUA
  - source ~/lua_install/bin/activate

cache:
  pip: true
  directories:
    - ~/lua_install

install:
  - luarocks install busted
  - luarocks install luacov
  - luarocks install cluacov
  - luarocks install luacov-coveralls
  - luarocks install luacheck

script:
  - make coverage LUA=lua
  - make check
  - make cloc

after_success:
- luacov-coveralls -e ~/lua_install
